name: Build Vue

on:
  push:
    branches:
      - main  # Adjust this to your main branch

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer@latest | node
          pnpm install

      - name: Build with VuePagesAction
        id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'Piero Neri'
          reponame: 'Pokedl'
          token: ${{ secrets.GITHUB_TOKEN }}
          cmd: 'pnpm run build'  # Adjust this to your build command
