name: CI/CD with Supabase and GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-supabase:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_API_KEY }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT }}
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy --project-ref $PROJECT_ID

  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GITHUB_EMAIL }}"
          git config --global user.name "${{ secrets.GITHUB_NAME }}"

      - name: Build for GitHub Pages
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git checkout gh-pages
          cp -r dist/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages

# Ajoutez d'autres étapes de votre flux de travail au besoin
